os: linux

# we need super user privileges, so we depend on the old travis-ci infrastructure
sudo: required

# we can install additional software
apt_packages:
# we download pdf2djvu to also generate a djvu file of our LaTeX source
- texlive-full
- pdf2djvu

script:
pdflatex testFile.tex 
after_success:

deploy:
provider: releases
user: "ajdinm"
password: "AjdiN13lol"
file: 
- testFile.pdf
- testFile.djvu
skip_cleanup: true
on: 
repo: ajdinm/TravisCITest