os: linux

# we need super user privileges, so we depend on the old travis-ci infrastructure
sudo: required

# we can install additional software
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-full
script:
- pdflatex testFile.tex 
after_success:

deploy:
provider: releases
user: "ajdinm"
password: "AjdiN13lol"
file: 
- testFile.pdf
- testFile.djvu
skip_cleanup: true
on: 
repo: ajdinm/TravisCITest