os: linux

# we need super user privileges, so we depend on the old travis-ci infrastructure
sudo: required

# we can install additional software
install:
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended pdf2djvu
script:
- pdflatex -interaction=nonstopmode testFile.tex 
- pdf2djvu -d 1200 -o testFile.djvu testFile.pdf
after_success:

deploy:

provider: releases
user: "ajdinm"
password: "AjdiN13lol"
file: 
- testFile.pdf
- testFile.djvu
skip_cleanup: true
on: 
repo: ajdinm/TravisCITest